import { ArgumentsHost, Catch, ExceptionFilter, HttpException } from '@nestjs/common';
import { Response } from 'express';

const CONFLICT_CODES = new Set([
  'GENERATOR_COMMAND_CONFLICT',
  'GENERATOR_CONTEXT_STALE',
  'DECISION_EVENT_IDEMPOTENCY_CONFLICT',
  'LEARNING_OUTCOME_IDEMPOTENCY_CONFLICT',
  'ROUTING_DECISION_STALE',
  'TEAM_SWITCH_CONTEXT_STALE',
  'DISCOVERY_NOT_WAITING',
  'DISCOVERY_NOT_IN_FEATURE_REVIEW',
  'DISCOVERY_PROMPTMASTER_NOT_READY',
  'DISCOVERY_PROMPTMASTER_NOT_LOCKED',
  'DISCOVERY_CHANGE_REQUIRES_REPLAN',
  'DISCOVERY_PROMPTMASTER_HAS_BLOCKERS',
  'DISCOVERY_PROMPTMASTER_NEEDS_DECISION',
  'DISCOVERY_PROMPTMASTER_SECTIONS_INCOMPLETE',
  'DISCOVERY_PROMPTMASTER_REVIEW_INCOMPLETE',
  'MARKETPLACE_SOLUTION_SLUG_TAKEN',
  'MARKETPLACE_REFERENCE_PROMPTMASTER_NOT_LOCKED',
  'MARKETPLACE_REFERENCE_MISSION_NOT_GENERATED',
  'MARKETPLACE_SOLUTION_VERSION_NOT_VERIFIED',
  'MARKETPLACE_CUSTOMIZATION_PLAN_NOT_APPROVED',
  'MARKETPLACE_CUSTOMIZATION_POLICY_VIOLATION',
  'MARKETPLACE_PRICING_QUOTE_EXPIRED',
  'MARKETPLACE_CUSTOMIZATION_PLAN_ALREADY_APPROVED',
  'MARKETPLACE_CUSTOMIZATION_PLAN_REJECTED',
  'MARKETPLACE_PUBLISHED_SOLUTION_REVIEW_DRIFT',
  'MARKETPLACE_REVIEW_NO_MECHANICAL_TARGET',
  'MISSION_PROMPTMASTER_NOT_LOCKED',
  'MISSION_NOT_GENERATED',
  'GENERATION_NOT_READY',
  'ARCHITECTURE_REVIEW_NOT_APPROVED',
  'DELIVERY_NOT_ELIGIBLE',
  'SECURITY_GATE_FAILED',
  'GITHUB_NOT_CONFIGURED',
  'GITHUB_REPO_NAME_TAKEN',
  'GITLAB_NOT_CONFIGURED',
  'GITLAB_REPO_NAME_TAKEN',
  'APPROVAL_ALREADY_DECIDED',
  'APPROVAL_SUBJECT_DRIFT',
  'APPROVAL_SUBJECT_NOT_PENDING',
  'ARCHITECTURE_HUMAN_APPROVAL_REQUIRED',
  'MISSION_ASSEMBLY_IN_PROGRESS',
  'MISSION_JOB_PLAN_DRIFT',
  'MISSION_JOB_NOT_READY',
  'MISSION_JOB_ROUTING_INPUT_DRIFT',
  'MISSION_JOB_ROUTING_STALE',
]);

const NOT_FOUND_CODES = new Set([
  'MISSION_NOT_FOUND',
  'DISCOVERY_NOT_FOUND',
  'REQUIREMENT_NOT_FOUND',
  'MARKETPLACE_SOLUTION_NOT_FOUND',
  'MARKETPLACE_SOLUTION_VERSION_NOT_FOUND',
  'MARKETPLACE_CUSTOMIZATION_PLAN_NOT_FOUND',
  'MARKETPLACE_PRICING_QUOTE_NOT_FOUND',
  'MISSION_GENERATION_NOT_STARTED',
  'ARCHITECTURE_REVIEW_NOT_STARTED',
  'GITHUB_PUSH_NOT_STARTED',
  'GITLAB_PUSH_NOT_STARTED',
  'APPROVAL_NOT_FOUND',
  'ARCHITECTURE_COMPOSITION_NOT_FOUND',
  'MISSION_JOB_NOT_FOUND',
]);

const SERVICE_UNAVAILABLE_CODES = new Set(['AI_EXPLANATION_UNAVAILABLE', 'DISCOVERY_AI_UNAVAILABLE', 'MARKETPLACE_CUSTOMIZER_AI_UNAVAILABLE', 'GITHUB_UNAVAILABLE', 'GITLAB_UNAVAILABLE']);

/**
 * Normalizes errors raised by the framework-neutral core services (plain `Error` whose
 * message is a stable domain code, e.g. GENERATOR_COMMAND_CONFLICT) into HTTP responses.
 * Mirrors the mapping already used by core/src/adapters/generator-http-server.ts so both
 * transports behave the same way.
 */
@Catch()
export class DomainErrorFilter implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost): void {
    const response = host.switchToHttp().getResponse<Response>();

    if (exception instanceof HttpException) {
      const status = exception.getStatus();
      response.status(status).json({ error: exception.message });
      return;
    }

    const code = exception instanceof Error ? exception.message : 'INTERNAL_ERROR';
    const status = CONFLICT_CODES.has(code) ? 409 : NOT_FOUND_CODES.has(code) ? 404 : SERVICE_UNAVAILABLE_CODES.has(code) ? 503 : 400;
    response.status(status).json({ error: code });
  }
}
