export type GeneratorState =
  | 'INTENT_PENDING' | 'INTENT_READY' | 'REQUIREMENTS_DRAFT' | 'REQUIREMENTS_APPROVED'
  | 'TOPOLOGY_PROPOSED' | 'TOPOLOGY_APPROVED' | 'SOLUTION_PLANNING' | 'SOLUTION_PROPOSED'
  | 'SOLUTION_APPROVED' | 'ARCHITECTURE_COMPOSING' | 'ARCHITECTURE_REVIEW'
  | 'ARCHITECTURE_APPROVED' | 'TEAM_COMPOSING' | 'TEAM_READY' | 'PIPELINE_PLANNING'
  | 'READY_FOR_EXECUTION' | 'ACTIVE' | 'BLOCKED' | 'CANCELLED' | 'COMPLETED';

export type ReplanReason = 'REQUIREMENTS_CHANGED' | 'USER_PREFERENCE_CHANGED' | 'RUNTIME_UNSUPPORTED' | 'COST_CONSTRAINT_CHANGED' | 'SECURITY_REQUIREMENT_CHANGED' | 'INTEGRATION_CHANGED' | 'SCOPE_EXPANSION_APPROVED';

export interface GeneratorMissionState {
  missionId: string;
  state: GeneratorState;
  version: number;
  lastReason?: ReplanReason;
}
